# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  # language: "en"
  nerdFontsVersion: "2"
  border: "rounded"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
