#!/data/data/com.termux/files/usr/bin/sh

termux-wake-lock

CYAN="$(printf '\033[36m')"; GREEN="$(printf '\033[32m')"; TAIL="$(printf '\033[0m')";
IP_ADDR=$(ifconfig -a 2>&1 | awk '/wlan0/{flag=1} flag && /inet /{print $2; exit}')
START_OK=$(cat <<- EOF
███████╗████████╗ █████╗ ██████╗ ████████╗
██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
███████╗   ██║   ███████║██████╔╝   ██║
╚════██║   ██║   ██╔══██║██╔══██╗   ██║
███████║   ██║   ██║  ██║██║  ██║   ██║
╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

 ██████╗ ██╗  ██╗
██╔═══██╗██║ ██╔╝
██║   ██║█████╔╝
██║   ██║██╔═██╗
╚██████╔╝██║  ██╗
 ╚═════╝ ╚═╝  ╚═╝
EOF
)
if command -v toilet > /dev/null; then
    IP_ADDR=$(printf "\n\n%s" "$(echo "$IP_ADDR" | toilet -f future --metal | sed 's/^/   /')")
    START_OK=$(echo "SSHD START OK" | toilet -f future --metal)
fi
CONNECT_COMMAND=$(cat <<- EOF
The server is running on port 8022.
Connect with the following command:


    ${GREEN}ssh${TAIL} -p 8022 ${IP_ADDR}

${TAIL}
EOF
)

check_command() {
    if ! command -v sshd > /dev/null; then
        echo "${CYAN}[WARN] \`sshd\` is not installed."
        echo
        echo "[WARN] Run 'pkg install -y openssh'.${TAIL}"
        return 1
    fi
}

start_sshd() {
    if [ $(pgrep sshd | wc -l) -le 0 ]; then
        if sshd; then cat <<EOF
${GREEN}
${START_OK}
${TAIL}
${CONNECT_COMMAND}
${GREEN}[OK] Started \`sshd\`.
${TAIL}
EOF
        fi
    else
        echo "${CYAN}[WARN] \`sshd\` has already been started.${TAIL}"
        echo "${CONNECT_COMMAND}"
    fi
}

if check_command; then
    start_sshd
fi

for i in $(seq 5 -1 1); do
    printf "Closing in %d seconds...\r" "$i"
    sleep 1
done
printf "\n"

