[manager]
prepend_keymap = [
    { on = "<A-w>", run = "quit", desc = "Quit the process" },
    { on = "<A-y>", run = "quit", desc = "Quit the process" },
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "d", run = "remove --permanently", desc = "Permanently delete selected files" },
    { on = "D", run = "remove", desc = "Trash selected files" },
]
