"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
edit = [
    { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'nvim %*', block = true, desc = "nvim (block)", for = "windows" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
    { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "code" },
]
prepend_fetchers = [
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" },
]

[preview]
image_delay = 0
